### ISSUE TITLE
VSCode: Go To Definition multiwork-root

### ISSUE THREAD

**Issue by valerio-brew** [felixfbecker/php-language-server#646] opened 2018-05-31 04:37 UTC
It seems that the "Go To Definition" across multiple Work-Root does not work properly.

I've 7 folders in my VS Workspace, all PHP.

I wait until indexing is completed, than I try "Go to Definition" for a function of my library, the system does not finds any definition.

I open the file in the editor, from that moment on it works.

The only weird thing I can notice is the startup error in DevTools for VSCode.

> [Extension Host] DEBUG     Checking PHPLS_ALLOW_XDEBUG
> DEBUG     The xdebug extension is not loaded
> 
> t.log @ /usr/share/code/resources/app/out/vs/workbench/workbench.main.js:263
> 

I don't know how to provide you an example, as it works with small folders (I've allowed 4GB for PHP)

valerio@beatrice:/work/projects/library$ find . | wc -l
29306
valerio@beatrice:/work/projects/library$ 

valerio@beatrice:/work/clients_www$ find . | wc -l
5441
valerio@beatrice:/work/clients_www$

**Comment by felixfbecker** [comment] 2018-05-31 17:37
Duplicate of https://github.com/felixfbecker/php-language-server/issues/513

**Closed by felixfbecker** 2018-05-31 17:37 UTC
