### ISSUE TITLE
foreach-as loop new variable doesn't get suggested

### ISSUE THREAD

**Issue by jens1o** [felixfbecker/php-language-server#279] opened 2017-02-04 20:24 UTC
When `php.suggest.basic` is set to `false`

Having the following snippet:
```php
<?php

$array = ['Hello World'];

foreach($array as $snippet) {
    echo $|; // enter your cursor here
}
```
`$snippet` doesn't get suggested

**Comment by felixfbecker** [comment] 2017-02-05 10:56
Duplicate of #200

**Closed by felixfbecker** 2017-02-05 10:56 UTC
