### ISSUE TITLE
PHP Language Server never stops parsing files

### ISSUE THREAD

**Issue by johnbillion** [felixfbecker/php-language-server#336] opened 2017-03-21 12:00 UTC
I have a project which contains around 38,000 files. 8,500 of them are `.php` files. The PHP Language Server is stuck in a loop parsing the PHP files, and does not complete.

Watching the `Output` of the PHP Language Server, it appears to parse all of the files but then starts again at the first directory in the project, with no additional output other than `Parsing <file>`.

What can I do to help debug this problem? I've had to disable the extension on this project as it's eating up my CPU :-)

There is one error that appears in the developer console:

```
extensionHost.ts:282 [Extension Host] TypeError: Return value of LanguageServer\DefinitionResolver::resolveExpressionNodeToType() must implement interface phpDocumentor\Reflection\Type, null returned in /Users/john/.vscode/extensions/felixfbecker.php-intellisense-1.1.3/vendor/felixfbecker/language-server/src/DefinitionResolver.php:445
Stack trace:
#0 /Users/john/.vscode/extensions/felixfbecker.php-intellisense-1.1.3/vendor/felixfbecker/language-server/src/DefinitionResolver.php(239): LanguageServer\DefinitionResolver->resolveExpressionNodeToType(Object(PhpParser\Node\Expr\FuncCall))
#1 /Users/john/.vscode/extensions/felixfbecker.php-intellisense-1.1.3/vendor/felixfbecker/language-server/src/NodeVisitor/ReferencesCollector.php(38): LanguageServer\DefinitionResolver->resolveReferenceNodeToFqn(Object(PhpParser\Node\Expr\MethodCall))
#2 /Users/john/.vscode/extensions/felixfbecker.php-intellisense-1.1.3/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(108): LanguageServer\NodeVisitor\ReferencesCollector->enterNode(Object(PhpParser\Node\Expr\MethodCall))
#3 /Users/john/.vscode/extensions/felixfbecker.php-intellisense-1.1.3/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(171): PhpParser\NodeTraverser->traverseNode(Object(PhpParser\Node\Expr\Assign))
#4 /Users/john/.vscode/extensions/felixfbecker.php-intellisense-1.1.3/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(101): PhpParser\NodeTraverser->traverseArray(Array)
#5 /Users/john/.vscode/extensions/felixfbecker.php-intellisense-1.1.3/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(171): PhpParser\NodeTraverser->traverseNode(Object(PhpParser\Node\Stmt\Foreach_))
#6 /Users/john/.vscode/extensions/felixfbecker.php-intellisense-1.1.3/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(101): PhpParser\NodeTraverser->traverseArray(Array)
#7 /Users/john/.vscode/extensions/felixfbecker.php-intellisense-1.1.3/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(171): PhpParser\NodeTraverser->traverseNode(Object(PhpParser\Node\Stmt\ClassMethod))
#8 /Users/john/.vscode/extensions/felixfbecker.php-intellisense-1.1.3/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(101): PhpParser\NodeTraverser->traverseArray(Array)
#9 /Users/john/.vscode/extensions/felixfbecker.php-intellisense-1.1.3/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(171): PhpParser\NodeTraverser->traverseNode(Object(PhpParser\Node\Stmt\Class_))
#10 /Users/john/.vscode/extensions/felixfbecker.php-intellisense-1.1.3/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(101): PhpParser\NodeTraverser->traverseArray(Array)
#11 /Users/john/.vscode/extensions/felixfbecker.php-intellisense-1.1.3/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(171): PhpParser\NodeTraverser->traverseNode(Object(PhpParser\Node\Stmt\Namespace_))
#12 /Users/john/.vscode/extensions/felixfbecker.php-intellisense-1.1.3/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(85): PhpParser\NodeTraverser->traverseArray(Array)
#13 /Users/john/.vscode/extensions/felixfbecker.php-intellisense-1.1.3/vendor/felixfbecker/language-server/src/PhpDocument.php(205): PhpParser\NodeTraverser->traverse(Array)
#14 /Users/john/.vscode/extensions/felixfbecker.php-intellisense-1.1.3/vendor/felixfbecker/language-server/src/PhpDocument.php(119): LanguageServer\PhpDocument->updateContent('<?php\n\nnamespac...')
#15 /Users/john/.vscode/extensions/felixfbecker.php-intellisense-1.1.3/vendor/felixfbecker/language-server/src/PhpDocumentLoader.php(134): LanguageServer\PhpDocument->__construct('file:///sites/w...', '<?php\n\nnamespac...', Object(LanguageServer\Index\Index), Object(LanguageServer\Parser), Object(phpDocumentor\Reflection\DocBlockFactory), Object(LanguageServer\DefinitionResolver))
#16 /Users/john/.vscode/extensions/felixfbecker.php-intellisense-1.1.3/vendor/felixfbecker/language-server/src/PhpDocumentLoader.php(113): LanguageServer\PhpDocumentLoader->create('file:///sites/w...', '<?php\n\nnamespac...')
#17 [internal function]: LanguageServer\PhpDocumentLoader->LanguageServer\{closure}()
#18 /Users/john/.vscode/extensions/felixfbecker.php-intellisense-1.1.3/vendor/sabre/event/lib/coroutine.php(70): Generator->send('<?php\n\nnamespac...')
#19 /Users/john/.vscode/extensions/felixfbecker.php-intellisense-1.1.3/vendor/sabre/event/lib/Promise.php(242): Sabre\Event\{closure}('<?php\n\nnamespac...')
#20 /Users/john/.vscode/extensions/felixfbecker.php-intellisense-1.1.3/vendor/sabre/event/lib/Loop/Loop.php(261): Sabre\Event\Promise->Sabre\Event\{closure}()
#21 /Users/john/.vscode/extensions/felixfbecker.php-intellisense-1.1.3/vendor/sabre/event/lib/Loop/Loop.php(215): Sabre\Event\Loop\Loop->runNextTicks()
#22 /Users/john/.vscode/extensions/felixfbecker.php-intellisense-1.1.3/vendor/sabre/event/lib/Loop/Loop.php(194): Sabre\Event\Loop\Loop->tick(true)
#23 /Users/john/.vscode/extensions/felixfbecker.php-intellisense-1.1.3/vendor/sabre/event/lib/Loop/functions.php(122): Sabre\Event\Loop\Loop->run()
#24 /Users/john/.vscode/extensions/felixfbecker.php-intellisense-1.1.3/vendor/felixfbecker/language-server/bin/php-language-server.php(102): Sabre\Event\Loop\run()
#25 {main}d.logExtensionHostMessage @ extensionHost.ts:282(anonymous function) @ extensionHost.ts:137emitTwo @ events.js:106emit @ events.js:191process.nextTick @ internal/child_process.js:744_combinedTickCallback @ internal/process/next_tick.js:67_tickCallback @ internal/process/next_tick.js:98
```

**Comment by felixfbecker** [comment] 2017-03-21 12:06
Duplicate of https://github.com/felixfbecker/php-language-server/issues/311

**Closed by felixfbecker** 2017-03-21 12:06 UTC

**Comment by maikel-cit** [comment] 2018-09-03 18:44
@felixfbecker This is still happening, updated version and #311 does not fix this.

**Comment by rinasek** [comment] 2018-09-04 10:06
I can confirm that this is still happening. I can bake a pizza on my laptop.

**Comment by pacotole** [comment] 2018-09-10 09:49
In my case, the parsing of php files stopped by disabling PHP IntelliSense extension

**Comment by egiesem** [comment] 2019-01-27 11:45
> In my case, the parsing of php files stopped by disabling PHP IntelliSense extension

that's true

**Comment by robrecord** [comment] 2019-02-19 10:43
I disabled PHP intellisense and it fixed the issue.

**Comment by jonathanslater** [comment] 2019-02-19 16:35
yep, uninstall php intellisense extension. it doesn't work properly.

**Comment by markusantonwolf** [comment] 2019-04-25 07:34
That's right -> in my case I had to **uninstall** the php intellisense extension to stop endless parsing...

**Comment by TylerBarnes** [comment] 2019-06-20 17:10
I'm not sure if this is helpful for this issue but there is a setting to lower the memory limit for the php language server. It's set to 4gb by default. If your computer doesn't have a lot of ram, you probably want to lower that.

![Screen Shot 2019-06-20 at 10 09 20 AM](https://user-images.githubusercontent.com/14190743/59867662-a0b7c200-9343-11e9-8aa4-ddcff6c364b7.png)

**Comment by GBeushausen** [comment] 2019-08-29 21:09
I also still have this issue. And it's creating dozens (9000+) of totally wrong error messages.

**Comment by almarrr** [comment] 2019-09-20 09:02
I have it since a few hours, it worked perfectly for months.

**Comment by krisdr** [comment] 2019-09-20 10:10
> I have it since a few hours, it worked perfectly for months.

Same here

**Comment by tochjunin** [comment] 2019-09-20 12:44
same problem with me, uninstalling php intellisense didnt help either.

**Comment by zeptoon** [comment] 2019-09-20 19:29
Also have this issue

**Comment by tonviet712** [comment] 2019-09-23 02:47
same here after update

**Comment by pucitos** [comment] 2019-09-23 12:29
alsi i have this issue

**Comment by jameswilson34** [comment] 2019-09-23 13:31
Me too - MAC fans are spinning triple time and VSC is nearly unusable.

**Comment by dave470003** [comment] 2019-09-23 16:02
i also have this issue after updating, was working fine before

**Comment by snikolaidis** [comment] 2019-09-23 20:33
Same here, can't stop parsing the files.

**Comment by chendujin** [comment] 2019-09-24 02:14
I also appeared after updating VSC. Is it a bug?

**Comment by JoeyFenny** [comment] 2019-09-24 05:36
Worked fine for me yesterday. Just started doing this today.

**Comment by Crayzo** [comment] 2019-09-24 16:26
Just uninstall PHP IntelliSence and install PHP Intelephense

**Comment by ithieund** [comment] 2019-09-25 01:27
> Just uninstall PHP IntelliSence and install PHP Intelephense

Thanks @Crayzo . PHP Intelephense is perfect!

**Comment by cyberorca** [comment] 2019-09-25 02:30
PHP intellisense is going nuts ... just uninstall this ram eater ..

**Comment by AhsanShabbir** [comment] 2019-09-29 09:14
I also had the same issue. Disabling PHP IntelliSence was the solution.

**Comment by wayne259** [comment] 2019-09-30 03:05
Same issue here, and resolve by disabling PHP Intelephense extension. Many thanks.

**Comment by calhaudev** [comment] 2019-10-03 11:47
DIsabled the PHP IntelliSense and the problem disappear. Thanks for the tip!

**Comment by zecka** [comment] 2019-10-12 10:13
And if I want to keep IntelliSense ? Any way to exclude folder from parsing ?

**Comment by almarrr** [comment] 2019-10-15 09:45
The problem is back again, worked about perfect for 4 weeks.

**Comment by TylerBarnes** [comment] 2019-10-16 23:01
Intelephense is the way to go! Thanks to everyone here that recommended it!

**Comment by emilpriverrc** [comment] 2019-10-21 08:38
Have the problem aswell :(

**Comment by ronaldtveen** [comment] 2019-10-22 13:01
Switched to Intelephense as well.

**Comment by rlavooij** [comment] 2019-10-31 10:35
Intelephense here too!

**Comment by TylerBarnes** [comment] 2019-10-31 16:28
Seems like vscode-intellisense (or php-language-server?) should be deprecated since it performs so poorly compared to alternatives. It's a very frustrating experience trying to figure out which extension is eating your computer alive

I originally thought for many months that vscode just didn't work well with PHP, so this extension actually negatively impacted my ability to do my job since I couldn't properly work on PHP code and didn't want to leave VSCode.

**Comment by robertsheacole** [comment] 2019-11-07 15:12
bye bye PHP intellisense...

**Comment by ajkasuri** [comment] 2019-11-13 09:10
PHP IntelliSense extension should be disabled to stop parsing the PHP files.

**Comment by nop1984** [comment] 2019-11-15 18:11
> Just uninstall PHP IntelliSence and install PHP Intelephense
this helped me https://github.com/felixfbecker/php-language-server/issues/336#issuecomment-534637224

**Comment by digisavvy** [comment] 2019-11-21 04:30
Oh goodness, disabled php intellisense.

**Comment by Jeeva-Rathinam** [comment] 2019-11-21 06:41
Any one help me> What is parsing file mean?

**Comment by MegaphoneJon** [comment] 2019-11-25 17:38
I experience this problem on some repos and not others.  I suspect it's down to submodules rather than size, though I'm going to disable for now.  Hopefully this gives others who need to troubleshoot this more a direction.

**Comment by wunluv** [comment] 2019-11-28 18:19
Thanks. Disabling php intellisense worked for me too.

**Comment by raftaar1191** [comment] 2019-12-02 06:24
Thanks. Disabling php intellisense worked for me too. But I need php intellisense extensions

**Comment by TylerBarnes** [comment] 2019-12-03 00:03
@raftaar1191 use intelliphense

**Comment by Brugui7** [comment] 2019-12-03 13:04
Same here, unistalling intelillisense makes everything work fine.
I recommend to install  inteliphpsense instead.

**Comment by altayevrim** [comment] 2019-12-10 09:22
> @raftaar1191 use intelliphense

thanks for suggestion

**Comment by TinoCle** [comment] 2020-07-15 19:29
Intelephense uses to eat my computer resources, It's a shame that PHP Intellisense takes so long to parse my files.

**Comment by manugarcia101** [comment] 2020-08-10 13:56
Disable PHP Intelisense for all vscode or at least for big workspaces (The bigger the workspace the worst...) 👍

**Comment by Lakshay11** [comment] 2021-02-10 12:48
Literally, you don't need a room heater, if you have PHP intellisense enabled and working on a Drupal site

**Comment by MarthinusBotha** [comment] 2022-01-26 09:38
> I'm not sure if this is helpful for this issue but there is a setting to lower the memory limit for the php language server. It's set to 4gb by default. If your computer doesn't have a lot of ram, you probably want to lower that.
> 
> ![Screen Shot 2019-06-20 at 10 09 20 AM](https://user-images.githubusercontent.com/14190743/59867662-a0b7c200-9343-11e9-8aa4-ddcff6c364b7.png)

I have updated both my Memory Settings for PHP Intellisense and the memory used for Large Files for Visual Code to use less memory and it seems to make things faster and doesn't always the Language server the whole time on my site and my Total Memory usage has also reduced

**Comment by draeockenden** [comment] 2024-11-01 04:41
I am getting this too in 2024 with PHP Intelephense
