### ISSUE TITLE
support 7.1 nullable types in return type

### ISSUE THREAD

**Issue by andares** [felixfbecker/php-language-server#353] opened 2017-04-17 03:56 UTC
declare return type with nullable types is still crash.

like the code:

```php
public function save(string $dir): ?string {
    return $dir ?: null;
}
```

**Comment by jens1o** [comment] 2017-04-17 07:00
yep, because #292 is not merged, yet. Duplicate of #290.

**Comment by felixfbecker** [comment] 2017-04-17 08:09
@jens1o fell free to tag issues and close duplicates

**Closed by felixfbecker** 2017-04-17 08:09 UTC
Labels: Resolution: Duplicate
