### ISSUE TITLE
Connection to server got closed. 

### ISSUE THREAD

**Issue by fappels** [felixfbecker/php-language-server#365] opened 2017-04-24 09:17 UTC
After update PHP intellisense to 1.2.0 the connection always closes after parsing a while. The server restarts, so language server is continuous parsing. I have around 4500 files in my project.

[Info  - 11:10:14 AM] Connection to server got closed. Server will restart.

**Comment by felixfbecker** [comment] 2017-04-24 09:37
This is very likely a duplicate of https://github.com/felixfbecker/php-language-server/issues/364, but can't tell without a stack trace.

**Closed by felixfbecker** 2017-04-24 09:37 UTC
