### ISSUE TITLE
At start "Indexing project for definitions and static references" only working on first folder in workspace

### ISSUE THREAD

**Issue by lqq4826** [felixfbecker/php-language-server#647] opened 2018-06-03 13:32 UTC
At start of vscode,  php-language-server in output says "Indexing project for definitions and static references" only working on first folder in workspace, so when i click Go to Definition on files in other folders, it will go to the definition which is in file of the first folder
could anyone help me to solve this problem? or give some guidelines?
im a php coders with many projects folders, i add them in a workspace……

**Comment by felixfbecker** [comment] 2018-06-04 16:42
Duplicate of https://github.com/felixfbecker/php-language-server/issues/513

**Closed by felixfbecker** 2018-06-04 16:42 UTC

**Comment by lqq4826** [comment] 2018-06-08 09:49
OK,i will pay attention to this, thx!!
