### ISSUE TITLE
Crash because Definition->type is null for a function

### ISSUE THREAD

**Issue by lumpysimon** [felixfbecker/php-language-server#311] opened 2017-02-20 17:33 UTC
Indexing a WordPress site, PHP7.1.1 on OSX, after about 15 mins of indexing I'm getting the `The PHP Language Server server crashed 5 times in the last 3 minutes. The server will not be restarted` error. Here's the stack trace:

````
extensionHost.ts:282 [Extension Host] TypeError: Return value of LanguageServer\DefinitionResolver::resolveExpressionNodeToType() must implement interface phpDocumentor\Reflection\Type, null returned in /Users/myuserhere/.vscode/extensions/felixfbecker.php-intellisense-1.1.2/vendor/felixfbecker/language-server/src/DefinitionResolver.php:444
Stack trace:
#0 /Users/myuserhere/.vscode/extensions/felixfbecker.php-intellisense-1.1.2/vendor/felixfbecker/language-server/src/DefinitionResolver.php(238): LanguageServer\DefinitionResolver->resolveExpressionNodeToType(Object(PhpParser\Node\Expr\FuncCall))
#1 /Users/myuserhere/.vscode/extensions/felixfbecker.php-intellisense-1.1.2/vendor/felixfbecker/language-server/src/NodeVisitor/ReferencesCollector.php(38): LanguageServer\DefinitionResolver->resolveReferenceNodeToFqn(Object(PhpParser\Node\Expr\MethodCall))
#2 /Users/myuserhere/.vscode/extensions/felixfbecker.php-intellisense-1.1.2/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(108): LanguageServer\NodeVisitor\ReferencesCollector->enterNode(Object(PhpParser\Node\Expr\MethodCall))
#3 /Users/myuserhere/.vscode/extensions/felixfbecker.php-intellisense-1.1.2/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(171): PhpParser\NodeTraverser->traverseNode(Object(PhpParser\Node\Expr\Assign))
#4 /Users/myuserhere/.vscode/extensions/felixfbecker.php-intellisense-1.1.2/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(101): PhpParser\NodeTraverser->traverseArray(Array)
#5 /Users/myuserhere/.vscode/extensions/felixfbecker.php-intellisense-1.1.2/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(171): PhpParser\NodeTraverser->traverseNode(Object(PhpParser\Node\Stmt\If_))
#6 /Users/myuserhere/.vscode/extensions/felixfbecker.php-intellisense-1.1.2/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(101): PhpParser\NodeTraverser->traverseArray(Array)
#7 /Users/myuserhere/.vscode/extensions/felixfbecker.php-intellisense-1.1.2/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(171): PhpParser\NodeTraverser->traverseNode(Object(PhpParser\Node\Stmt\Foreach_))
#8 /Users/myuserhere/.vscode/extensions/felixfbecker.php-intellisense-1.1.2/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(101): PhpParser\NodeTraverser->traverseArray(Array)
#9 /Users/myuserhere/.vscode/extensions/felixfbecker.php-intellisense-1.1.2/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(171): PhpParser\NodeTraverser->traverseNode(Object(PhpParser\Node\Stmt\Foreach_))
#10 /Users/myuserhere/.vscode/extensions/felixfbecker.php-intellisense-1.1.2/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(101): PhpParser\NodeTraverser->traverseArray(Array)
#11 /Users/myuserhere/.vscode/extensions/felixfbecker.php-intellisense-1.1.2/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(171): PhpParser\NodeTraverser->traverseNode(Object(PhpParser\Node\Stmt\ClassMethod))
#12 /Users/myuserhere/.vscode/extensions/felixfbecker.php-intellisense-1.1.2/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(101): PhpParser\NodeTraverser->traverseArray(Array)
#13 /Users/myuserhere/.vscode/extensions/felixfbecker.php-intellisense-1.1.2/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(171): PhpParser\NodeTraverser->traverseNode(Object(PhpParser\Node\Stmt\Class_))
#14 /Users/myuserhere/.vscode/extensions/felixfbecker.php-intellisense-1.1.2/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(101): PhpParser\NodeTraverser->traverseArray(Array)
#15 /Users/myuserhere/.vscode/extensions/felixfbecker.php-intellisense-1.1.2/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(171): PhpParser\NodeTraverser->traverseNode(Object(PhpParser\Node\Stmt\If_))
#16 /Users/myuserhere/.vscode/extensions/felixfbecker.php-intellisense-1.1.2/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(85): PhpParser\NodeTraverser->traverseArray(Array)
#17 /Users/myuserhere/.vscode/extensions/felixfbecker.php-intellisense-1.1.2/vendor/felixfbecker/language-server/src/PhpDocument.php(205): PhpParser\NodeTraverser->traverse(Array)
#18 /Users/myuserhere/.vscode/extensions/felixfbecker.php-intellisense-1.1.2/vendor/felixfbecker/language-server/src/PhpDocument.php(119): LanguageServer\PhpDocument->updateContent('<?php\n\n/*\n\tPlug...')
#19 /Users/myuserhere/.vscode/extensions/felixfbecker.php-intellisense-1.1.2/vendor/felixfbecker/language-server/src/PhpDocumentLoader.php(134): LanguageServer\PhpDocument->__construct('file:///private...', '<?php\n\n/*\n\tPlug...', Object(LanguageServer\Index\Index), Object(LanguageServer\Parser), Object(phpDocumentor\Reflection\DocBlockFactory), Object(LanguageServer\DefinitionResolver))
#20 /Users/myuserhere/.vscode/extensions/felixfbecker.php-intellisense-1.1.2/vendor/felixfbecker/language-server/src/PhpDocumentLoader.php(113): LanguageServer\PhpDocumentLoader->create('file:///private...', '<?php\n\n/*\n\tPlug...')
#21 [internal function]: LanguageServer\PhpDocumentLoader->LanguageServer\{closure}()
#22 /Users/myuserhere/.vscode/extensions/felixfbecker.php-intellisense-1.1.2/vendor/sabre/event/lib/coroutine.php(70): Generator->send('<?php\n\n/*\n\tPlug...')
#23 /Users/myuserhere/.vscode/extensions/felixfbecker.php-intellisense-1.1.2/vendor/sabre/event/lib/Promise.php(242): Sabre\Event\{closure}('<?php\n\n/*\n\tPlug...')
#24 /Users/myuserhere/.vscode/extensions/felixfbecker.php-intellisense-1.1.2/vendor/sabre/event/lib/Loop/Loop.php(261): Sabre\Event\Promise->Sabre\Event\{closure}()
#25 /Users/myuserhere/.vscode/extensions/felixfbecker.php-intellisense-1.1.2/vendor/sabre/event/lib/Loop/Loop.php(215): Sabre\Event\Loop\Loop->runNextTicks()
#26 /Users/myuserhere/.vscode/extensions/felixfbecker.php-intellisense-1.1.2/vendor/sabre/event/lib/Loop/Loop.php(194): Sabre\Event\Loop\Loop->tick(true)
#27 /Users/myuserhere/.vscode/extensions/felixfbecker.php-intellisense-1.1.2/vendor/sabre/event/lib/Loop/functions.php(122): Sabre\Event\Loop\Loop->run()
#28 /Users/myuserhere/.vscode/extensions/felixfbecker.php-intellisense-1.1.2/vendor/felixfbecker/language-server/bin/php-language-server.php(102): Sabre\Event\Loop\run()
#29 {main}
d.logExtensionHostMessage @ extensionHost.ts:282
(anonymous function) @ extensionHost.ts:137
emitTwo @ events.js:106
emit @ events.js:191
process.nextTick @ internal/child_process.js:744
_combinedTickCallback @ internal/process/next_tick.js:67
_tickCallback @ internal/process/next_tick.js:98
messageService.ts:126 The PHP Language Server server crashed 5 times in the last 3 minutes. The server will not be restarted.
e.doShow @ messageService.ts:126
e.show @ messageService.ts:105
(anonymous function) @ mainThreadMessageService.ts:55
n.Class.derive._oncancel @ winjs.base.raw.js:1641
t.$showMessage @ mainThreadMessageService.ts:25
e.handle @ abstractThreadService.ts:34
s @ ipcRemoteCom.ts:275
f @ ipcRemoteCom.ts:231
_combinedTickCallback @ internal/process/next_tick.js:67
_tickCallback @ internal/process/next_tick.js:98
````

**Comment by felixfbecker** [comment] 2017-02-20 17:35
Probably fixed by #292, which seems to have broken a test though. If you wanna look into that I can merge it, don't have time right now

**Comment by lumpysimon** [comment] 2017-02-20 17:48
I would help if I could, but it's way outside my field of knowledge I'm afraid.

**Comment by johnrom** [comment] 2017-02-21 19:39
This is not fixed by #292

**Comment by johnrom** [comment] 2017-02-21 19:51
@felixfbecker 

To fix this, [this line](https://github.com/felixfbecker/php-language-server/blob/c3debf4494742dbbe55b8b920f222e3af29a98e9/src/DefinitionResolver.php#L443) should check if `$def->type` is null:

```
$def = $this->index->getDefinition($fqn, true);

if ($def !== null && $def->type !== null) {
    return $def->type;
}
```

**Comment by felixfbecker** [comment] 2017-02-21 19:54
@johnrom thanks for looking into this, but the real issue is that `$def->type` is `null` in the `Definition` object, not that case is not handled.

**Comment by johnrom** [comment] 2017-02-21 19:56
I figured that was probably a problem (but I'll survive without that fix for now :) ). I have a file that causes this issue, if you'd like me to attach it.

**Comment by Talv** [comment] 2017-04-01 19:26
I did some digging on this. The issue is actually pretty trivial. It occurs for non namespaced symbols, where functions and classes have clashing names.

Shortest snippet of code that will trigger exception:

```php
class acf_local {
}
acf_local()->enabled;
```

When trying to resolve type definition of ```acf_local()``` it incorrectly assumes it's ```clas acf_local```. Obviously class doesn't define ```->type```, as it is type itself - thus the exception.
It happens because of missing ```()``` [here](https://github.com/felixfbecker/php-language-server/blob/4d0a0a2a1053111acb7d3d03d36b927ad9b56b76/src/DefinitionResolver.php#L449).
It doesn't occur for namespaced symbols because they have ```namespacedName``` attribute set (correctly) in [different part of code](https://github.com/felixfbecker/php-language-server/blob/4d0a0a2a1053111acb7d3d03d36b927ad9b56b76/src/DefinitionResolver.php#L844).

**Closed** 2017-04-01 23:40 UTC
Labels: Crash, Resolution: Fixed
