### ISSUE TITLE
No longer works after updating extension to 1.2.0, chain-crashing

### ISSUE THREAD

**Issue by belazor** [felixfbecker/php-language-server#361] opened 2017-04-22 15:14 UTC
> The PHP Language Server server crashed 5 times in the last 3 minutes. The server will not be restarted.

> [Error - 4:13:02 PM] Connection to server got closed. Server will not be restarted.

What information do you need in order to resolve this issue?

**Comment by felixfbecker** [comment] 2017-04-22 15:17
A stack trace at least. Have you checked the dev tools?

**Comment by belazor** [comment] 2017-04-22 15:20
I didn't know how to open dev tools, I worked it out.

> extensionHost.ts:284 [Extension Host] TypeError: Return value of LanguageServer\DefinitionResolver::resolveExpressionNodeToType() must implement interface phpDocumentor\Reflection\Type, null returned in /Users/filliph/.vscode/extensions/felixfbecker.php-intellisense-1.2.0/vendor/felixfbecker/language-server/src/DefinitionResolver.php:466
Stack trace:
#0 /Users/filliph/.vscode/extensions/felixfbecker.php-intellisense-1.2.0/vendor/felixfbecker/language-server/src/DefinitionResolver.php(811): LanguageServer\DefinitionResolver->resolveExpressionNodeToType(Object(PhpParser\Node\Expr\ConstFetch))
#1 /Users/filliph/.vscode/extensions/felixfbecker.php-intellisense-1.2.0/vendor/felixfbecker/language-server/src/DefinitionResolver.php(139): LanguageServer\DefinitionResolver->getTypeFromNode(Object(PhpParser\Node\Stmt\PropertyProperty))
#2 /Users/filliph/.vscode/extensions/felixfbecker.php-intellisense-1.2.0/vendor/felixfbecker/language-server/src/NodeVisitor/DefinitionCollector.php(45): LanguageServer\DefinitionResolver->createDefinitionFromNode(Object(PhpParser\Node\Stmt\PropertyProperty), 'XF\\BbCode\\Proce...')
#3 /Users/filliph/.vscode/extensions/felixfbecker.php-intellisense-1.2.0/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(159): LanguageServer\NodeVisitor\DefinitionCollector->enterNode(Object(PhpParser\Node\Stmt\PropertyProperty))
#4 /Users/filliph/.vscode/extensions/felixfbecker.php-intellisense-1.2.0/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(101): PhpParser\NodeTraverser->traverseArray(Array)
#5 /Users/filliph/.vscode/extensions/felixfbecker.php-intellisense-1.2.0/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(171): PhpParser\NodeTraverser->traverseNode(Object(PhpParser\Node\Stmt\Property))
#6 /Users/filliph/.vscode/extensions/felixfbecker.php-intellisense-1.2.0/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(101): PhpParser\NodeTraverser->traverseArray(Array)
#7 /Users/filliph/.vscode/extensions/felixfbecker.php-intellisense-1.2.0/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(171): PhpParser\NodeTraverser->traverseNode(Object(PhpParser\Node\Stmt\Class_))
#8 /Users/filliph/.vscode/extensions/felixfbecker.php-intellisense-1.2.0/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(101): PhpParser\NodeTraverser->traverseArray(Array)
#9 /Users/filliph/.vscode/extensions/felixfbecker.php-intellisense-1.2.0/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(171): PhpParser\NodeTraverser->traverseNode(Object(PhpParser\Node\Stmt\Namespace_))
#10 /Users/filliph/.vscode/extensions/felixfbecker.php-intellisense-1.2.0/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(85): PhpParser\NodeTraverser->traverseArray(Array)
#11 /Users/filliph/.vscode/extensions/felixfbecker.php-intellisense-1.2.0/vendor/felixfbecker/language-server/src/PhpDocument.php(205): PhpParser\NodeTraverser->traverse(Array)
#12 /Users/filliph/.vscode/extensions/felixfbecker.php-intellisense-1.2.0/vendor/felixfbecker/language-server/src/PhpDocument.php(119): LanguageServer\PhpDocument->updateContent('<?php\r\n\r\nnamesp...')
#13 /Users/filliph/.vscode/extensions/felixfbecker.php-intellisense-1.2.0/vendor/felixfbecker/language-server/src/PhpDocumentLoader.php(134): LanguageServer\PhpDocument->__construct('file:///www/pub...', '<?php\r\n\r\nnamesp...', Object(LanguageServer\Index\Index), Object(LanguageServer\Parser), Object(phpDocumentor\Reflection\DocBlockFactory), Object(LanguageServer\DefinitionResolver))
#14 /Users/filliph/.vscode/extensions/felixfbecker.php-intellisense-1.2.0/vendor/felixfbecker/language-server/src/PhpDocumentLoader.php(113): LanguageServer\PhpDocumentLoader->create('file:///www/pub...', '<?php\r\n\r\nnamesp...')
#15 [internal function]: LanguageServer\PhpDocumentLoader->LanguageServer\{closure}()
#16 /Users/filliph/.vscode/extensions/felixfbecker.php-intellisense-1.2.0/vendor/sabre/event/lib/coroutine.php(70): Generator->send('<?php\r\n\r\nnamesp...')
#17 /Users/filliph/.vscode/extensions/felixfbecker.php-intellisense-1.2.0/vendor/sabre/event/lib/Promise.php(242): Sabre\Event\{closure}('<?php\r\n\r\nnamesp...')
#18 /Users/filliph/.vscode/extensions/felixfbecker.php-intellisense-1.2.0/vendor/sabre/event/lib/Loop/Loop.php(261): Sabre\Event\Promise->Sabre\Event\{closure}()
#19 /Users/filliph/.vscode/extensions/felixfbecker.php-intellisense-1.2.0/vendor/sabre/event/lib/Loop/Loop.php(215): Sabre\Event\Loop\Loop->runNextTicks()
#20 /Users/filliph/.vscode/extensions/felixfbecker.php-intellisense-1.2.0/vendor/sabre/event/lib/Loop/Loop.php(194): Sabre\Event\Loop\Loop->tick(true)
#21 /Users/filliph/.vscode/extensions/felixfbecker.php-intellisense-1.2.0/vendor/sabre/event/lib/Loop/functions.php(122): Sabre\Event\Loop\Loop->run()
#22 /Users/filliph/.vscode/extensions/felixfbecker.php-intellisense-1.2.0/vendor/felixfbecker/language-server/bin/php-language-server.php(102): Sabre\Event\Loop\run()
#23 {main}

**Comment by felixfbecker** [comment] 2017-04-22 15:21
Duplicate of #252

**Closed by felixfbecker** 2017-04-22 15:21 UTC

**Comment by felixfbecker** [comment] 2017-04-22 15:31
my bad, https://github.com/felixfbecker/php-language-server/issues/286
