### ISSUE TITLE
Invalid syntax error with <?=

### ISSUE THREAD

**Issue by joanhey** [felixfbecker/php-language-server#620] opened 2018-03-14 14:33 UTC
`<?=` is the short tag for `<?php echo`
And it's valid to use ',' for join
`<?= $var, $va2, 'Hello' ?>`
But it's marked like invalid

**Comment by felixfbecker** [comment] 2018-03-14 16:49
Could you post the output if php -i?

**Comment by TysonAndre** [comment] 2018-03-23 06:21
This looks to me like a duplicate of https://github.com/felixfbecker/php-language-server/issues/596 (Also `<?=` with commas)

**Comment by joanhey** [comment] 2018-03-24 10:04
Yes, it's a duplicate.  8P
And short echo tags () are always enabled from PHP 5.4

**Closed** 2018-03-24 10:05 UTC
