### ISSUE TITLE
IntelliSense always suggests "<?php" when in HTML

### ISSUE THREAD

**Issue by cstuder** [felixfbecker/php-language-server#372] opened 2017-05-02 15:19 UTC
Every time I close an HTML tag in a PHP file, IntelliSense suggests `<?php` as next string. 

![image](https://cloud.githubusercontent.com/assets/288493/25624756/b4549210-2f5a-11e7-9585-f016aeb74076.png)

This is distracting when writing HTML: When I want to enter a linebreak, I first have to remove the suggestion before hitting `Enter`.

Is there a possibility to remove this particular suggestion?

(Using PHP IntelliSense V1.2.1 in Visual Studio Code 1.11.2 on Windows 10, `php.suggest.basic` is set to `false`)

**Comment by felixfbecker** [comment] 2017-05-02 15:20
This is because we need to set the `triggerCharacters` to `>` because a sequence like `->` is not supported. See https://github.com/Microsoft/language-server-protocol/issues/138

**Comment by cstuder** [comment] 2017-05-03 07:07
Just found the responsable code line: https://github.com/felixfbecker/php-language-server/blob/master/src/CompletionProvider.php#L281

I would prefer to have the first condition removed:

    } else if ($pos == new Position(0, 0)) {

My question is: Am I the only one who is annoyed by this? (Or am I the only one editing HTML in PHP files ?)

**Comment by felixfbecker** [comment] 2017-05-03 07:08
I don't understand how removing that condition would help

**Comment by cstuder** [comment] 2017-05-03 07:34
Sorry, I didn't make myself clear. Currently, the conditions are like this:

            } else if ($node instanceof Node\Stmt\InlineHTML || $pos == new Position(0, 0)) {

If I understand this correctly, the `<?php`-completion triggers on InlineHTML nodes and when the cursor is at the beginning of a document.

I propose to remove the first condition, so that line would only trigger on the second condition:

    } else if ($pos == new Position(0, 0)) {

Before opening a pull request I would like to understand why this line is how it is and whether my propsal is actually wanted.

**Comment by felixfbecker** [comment] 2017-05-03 07:37
The line is how it is to propose a new opening tag inside HTML. That is as designed. The issue is just that the autocomplete pop up all the time because we need to set `>` as a trigger character.

**Comment by cstuder** [comment] 2017-05-03 09:47
Yes, so before we go around in further circles: Do you think my request to remove this autocomplete is reasonable and that I should try my hands on a pull request to remove it?

**Comment by felixfbecker** [comment] 2017-05-03 09:49
I don't think so, that is as designed - Microsoft needs to fix the trigger characters

**Comment by abeebola** [comment] 2017-06-19 07:53
Hello.... I am having this issue as well and it is annoying to be honest. Is there a workaround or something?

**Comment by felixfbecker** [comment] 2017-06-19 07:54
Express your need for this on https://github.com/Microsoft/language-server-protocol/issues/138 :)

**Comment by abeebola** [comment] 2017-06-19 07:56
Okay. I hope they do whatever is needed soon. Thanks.

**Comment by ingageco** [comment] 2017-07-29 17:06
Thanks for directing me here @felixfbecker - hopefully MS gets this fixed soon!

**Comment by technomav** [comment] 2017-09-09 12:25
@felixfbecker same this happening to me. But i don't think this is microsoft language issue because when i turn off the intellisense then there is no <?php suggestion. And after turn this on, this is keep starts showing.
I don't know the structure and process of intellisense so i am helpless.
Sir if you can fix it then please. :)

**Comment by Ciantic** [comment] 2017-09-09 13:05
Keep throwing the pressure on that issue: https://github.com/Microsoft/language-server-protocol/issues/138 - if there is enough annoyance maybe the Microsoft can prioritize fixing that.

**Comment by tangorboyz** [comment] 2017-10-16 15:41
Ya, for example sometimes in php file we also include html, so the trigger for auto completion or IntelliSense should only work inside php tag (<?php ?>). If this is by design from vscode, then we should make a request for it.

**Comment by tangorboyz** [comment] 2017-10-16 15:53
this also happen in vscode. the suggestion for <?php also appear even after closing php tag (?>).
The problem doesn't happen after the extension has been disabled.

**Comment by tangorboyz** [comment] 2017-10-16 16:07
[](https://github.com/Microsoft/vscode/issues/14166)
You already did it.

**Comment by bcorcoran** [comment] 2017-10-30 21:33
Just came here to voice my displeasure. IMHO this suggestion needs to be removed until it can be turned into an option.

It suggests `<?php` when I type literally any character. 

This is a somewhat useless suggestion, anyway. Nobody is saving an appreciable amount of time by `<?php` being autocompleted. I am (we all are, I suspect), however, wasting time by having to clean up all the times I forget to hit escape and this garbage gets inserted.

**Closed** 2017-11-16 06:38 UTC
Labels: enhancement

**Comment by renoirfaria** [comment] 2017-11-29 00:14
Since we have no alternatives i would like to vote to remove `<?php` sugestion until we have news from Microsoft/language-server-protocol#138

It is annoying so much everyone.

**Comment by jens1o** [comment] 2017-11-29 06:41
@renoirfaria It is already implemented?

**Comment by abeebola** [comment] 2017-11-29 07:33
Nice. The feature was never needed in my opinion

**Comment by renoirfaria** [comment] 2017-11-29 15:41
@jens1o it is? I am telling it since my Atom IDE keeps suggesting it.

**Comment by jens1o** [comment] 2017-11-29 15:47
@renoirfaria https://github.com/atom/ide-php/issues/47 It still needs to support the feature ;)

**Comment by NikosK72** [comment] 2017-12-15 07:56
Could you please tosh it? It is so annoying that one can barely work with it.

**Comment by bcorcoran** [comment] 2017-12-20 19:09
I will keep updating this thread with the new snippet to remove/comment until it's fixed:

Remove/comment these lines as of 12/20

https://github.com/felixfbecker/php-language-server/blob/9eea26df711920a7e04d4894fc4b9263ee783e11/src/CompletionProvider.php#L176-L181

**Comment by Jensen0710** [comment] 2018-02-01 21:20
Is it supposed to be fixed? Because it sure aren't for me...

**Comment by jens1o** [comment] 2018-02-02 18:08
@Jensen0710 Yes it is, but vscode still doesn't support it.

**Comment by valentinocossar** [comment] 2018-02-06 15:16
Same for me, the problem of the suggest persists.

**Comment by bcorcoran** [comment] 2018-02-06 18:53
Still not sure why you don't just remove the lines I outlined? Nobody is saving time by having `<?php` auto-suggested. We are WASTING time having to hit escape or click out of the suggestion every time we type an HTML tag. @felixfbecker can you explain why you can't just remove this?

https://github.com/felixfbecker/php-language-server/blob/9eea26df711920a7e04d4894fc4b9263ee783e11/src/CompletionProvider.php#L176-L181

**Comment by jens1o** [comment] 2018-02-06 19:04
> I would be fine with a PR defaulting to not propose it inside HTML if the CompletionContext was not sent (I think the suggestion at the very beginning of the file should be kept as that is reasonable).

I'm going to do this now, so I don't get my notifications spammed with this (overstated) issue.

**Comment by felixfbecker** [comment] 2018-02-06 19:07
The vscode developers introduced the CompletionContext themselves, but you can always express to them that there is a desire to have it implemented

**Comment by valentinocossar** [comment] 2018-02-06 19:10
@felixfbecker @jens1o Sorry to bother you, I'm new to VS Code. So we have to wait for the fix, to consider this issue really solved? 🙂

**Comment by felixfbecker** [comment] 2018-02-06 19:14
From a language server standpoint, assuming a spec compliant client, there is no issue in the language server.
From a vscode user perspective, you'll either need to wait until vscode implements the parameter, or help out on the workaround I suggested.

**Comment by WraithKenny** [comment] 2018-02-06 19:15
@felixfbecker I'd basically ***never*** expect the `<?php` in the **html** context, except for possibly at the beginning of a file. The only other time it might be expected is immediately after switching from **php** context to **html** context via `?>`. Generally tho, the suggestion of `<?php` even in those cases is of limited advantage.

**Comment by NikosK72** [comment] 2018-02-07 07:59
That tinny <?php thing is of minor importance when there is a gazillion of others to take care of. On the contrary, when it pops up at the most inappropriate moments it can cause mistakes. Please remove it permanently.

**Comment by cstuder** [comment] 2018-02-07 08:16
As the person who opened this issue I would like everybody to please relax. Pull requests are on their way.

You can [upvote on the issue itself](https://github.com/felixfbecker/php-language-server/issues/372#issue-225729096) if you're bothered by the current behaviour.

@felixfbecker Thanks for you work and patience.

**Comment by bcorcoran** [comment] 2018-02-07 22:33
@felixfbecker I am using Atom. This should illustrate why the `<?php` suggestion is irritating. Should I hit enter to try to get to a new line, I will end up with `<div<?php`

![screen shot 2018-02-07 at 17 31 55](https://user-images.githubusercontent.com/313697/35945100-002355dc-0c2d-11e8-8d9a-d91713e2e42e.png)

**Comment by felixfbecker** [comment] 2018-02-07 22:34
@bcorcoran what version of ide-php do you use?

**Comment by bcorcoran** [comment] 2018-02-07 22:34
Latest, I literally just updated a few minutes ago.

**Comment by felixfbecker** [comment] 2018-02-07 22:35
Could you please still tell me the version number

**Comment by bcorcoran** [comment] 2018-02-07 22:35
0.7.5

**Comment by felixfbecker** [comment] 2018-02-07 22:37
Is that an automatic suggestion or did you invoke it with Cmd+Space? Could you post LSP logs?

**Comment by bcorcoran** [comment] 2018-02-07 22:37
It's automatic. How do I get LSP logs?

**Comment by felixfbecker** [comment] 2018-02-07 22:41
I don't know, I don't use Atom

**Comment by bcorcoran** [comment] 2018-02-07 22:49
Anyway, the solution is to delete/comment out the lines I have been posting. In the rare case that a `<?php` suggestion would be useful, I am happy to type it out manually rather than deal with it being suggested for literally any html tag. Sorry for being irritating about this, but it's an irritating issue.

**Comment by felixfbecker** [comment] 2018-02-07 23:09
> rather than deal with it being suggested for literally any html tag

There should be no more autotriggered suggestions on the `>` in a client like Atom ide-php v0.7.5 (which should send CompletionContext) not in VS Code (which sends no CompletionContext). This is unit tested in the language server. To help you further I would have to see LSP logs.

**Comment by bcorcoran** [comment] 2018-02-08 01:38
It triggers with any < and doesn't go away if you type other characters. That was what I was trying to illustrate with the screenshot.

1. Type <
2. <?php suggestion shows up
3. Type anything else
4. <?php suggestion does not go away.

I think the <?php suggestion should go away if you don't type <?php

**Comment by felixfbecker** [comment] 2018-02-08 01:40
I see that you also get a suggestion for `div`. Does that disappear if you don't type `div`? If not, then that sounds more like an Atom issue
