### ISSUE TITLE
Goto label support

### ISSUE THREAD

**Issue by pelallemant** [felixfbecker/php-language-server#619] opened 2018-03-12 18:38 UTC
Hi,

php-language-server diagnoses me some error in cache files generated by symfony3.
Went into the code, and figured out that there are error with goto label, which are not fully supported by php-language-server, even if the file works with /usr/bin/php.

It happens when the label is declared at the end of a condition.

```
if(1) {
  label_1: // seems to be handled

    echo "test\n";

  label_which_fails: // parsing fails here, error is "Unexpected }"
}
```

Hope it won't be too hard to add into your grammar.

**Comment by TysonAndre** [comment] 2018-03-23 06:19
I'm pretty sure this is a duplicate of https://github.com/felixfbecker/php-language-server/issues/613

**Closed** 2018-03-23 07:29 UTC
