### ISSUE TITLE
HTML tags in the help signature issue

### ISSUE THREAD

**Issue by EmranMR** [felixfbecker/php-language-server#614] opened 2018-02-28 17:19 UTC
Hi,
I am not sure whether this is a bug or i messed up the setting somewhere. Why do I get HTML tags in the help signature as shown in the image... is there a workaround to sort it? 
It happens in all my pop ups!

![screen shot 2018-02-28 at 17 14 48](https://user-images.githubusercontent.com/11975985/36801947-4a57723a-1cab-11e8-9e53-c27fd9d2b3f0.png)

**Comment by felixfbecker** [comment] 2018-02-28 18:23
Duplicate of https://github.com/Microsoft/vscode/issues/40607

**Closed by felixfbecker** 2018-02-28 18:23 UTC
