### ISSUE TITLE
Trait completion 

### ISSUE THREAD

**Issue by Kazimazi** [felixfbecker/php-language-server#700] opened 2019-01-25 11:59 UTC
Currently the only flaw I see in php-language-server is that it doesn't provide completion for methods used from traits. Sometimes that's the only reason I use phpstorm instead of vim or vscode. Is there a barrier in solving the problem? If not then people might offer help.
Related: #331

**Comment by felixfbecker** [comment] 2019-01-25 12:54
Duplicate of #331

**Closed as completed by felixfbecker** 2019-01-25 12:54 UTC
