### ISSUE TITLE
Parsing issue of ".php" folder

### ISSUE THREAD

**Issue by zschopper** [felixfbecker/php-language-server#334] opened 2017-03-16 19:16 UTC
If I have a folder with name ".php" I got this message during parsing workspace files:

[Error - 20:08:28] Error parsing file:///c:/projects/sample/.php: ErrorException: file_get_contents(c:\projects\sample\.php): failed to open stream: Permission denied in C:\tools\VSCode\Data\code\extensions\felixfbecker.php-intellisense-1.1.3\vendor\felixfbecker\language-server\src\ContentRetriever\FileSystemContentRetriever.php:22

Not too important and common issue, but I think it would be good if you know about it.

Good job, I love VSCode with your extension, thx for your efforts :)

(ps: I have portable VSCode (1.10.2) with up-to-date plugins.)

**Comment by jens1o** [comment] 2017-03-16 19:41
duplicate of #306

**Comment by felixfbecker** [comment] 2017-03-16 20:00
thanks @jens1o

**Closed by felixfbecker** 2017-03-16 20:00 UTC
