### ISSUE TITLE
HTML tags shown in hover information

### ISSUE THREAD

**Issue by JohnstonCode** [felixfbecker/php-language-server#674] opened 2018-09-27 10:53 UTC
When hovering over some PHP functions the tooltip shows HTML tags

![image](https://user-images.githubusercontent.com/10222719/46141449-da8fe800-c24b-11e8-94df-b9aa48a9b336.png)

**Comment by felixfbecker** [comment] 2018-09-27 11:06
Duplicate of https://github.com/Microsoft/vscode/issues/40607

**Closed** 2018-09-27 11:06 UTC

**Comment by JohnstonCode** [comment] 2018-09-27 11:07
Yeah sorry also found https://github.com/felixfbecker/php-language-server/issues/288
