### ISSUE TITLE
Any way to skip files/folders from parsing?

### ISSUE THREAD

**Issue by sebet** [felixfbecker/php-language-server#285] opened 2017-02-07 15:26 UTC
I use _Visual Studio Code_ to work with WordPress projects. My workspaces are usually within the WordPress root folder. This problem with this setup is that the language server parses all the files inside the workspace.

Is there a way to exclude some of these files or folders from the parser?

**Comment by felixfbecker** [comment] 2017-02-07 15:28
Duplicate of #159

**Closed by felixfbecker** 2017-02-07 15:28 UTC
