### ISSUE TITLE
Show doc parameters/others

### ISSUE THREAD

**Issue by natanfelles** [felixfbecker/php-language-server#525] opened 2017-11-13 23:50 UTC
Like PhpStorm do:

![captura de tela de 2017-11-11 23-24-38](https://user-images.githubusercontent.com/3011423/32755423-5aeabd8e-c8bc-11e7-8a1b-a40bbd776306.png)

**Comment by felixfbecker** [comment] 2017-11-13 23:51
Duplicate of #18

**Closed by felixfbecker** 2017-11-13 23:51 UTC
