### ISSUE TITLE
No rename (refactor) functionality

### ISSUE THREAD

**Issue by darthrevan13** [felixfbecker/php-language-server#597] opened 2018-02-13 14:53 UTC
Hello,
I'm using neovim with [autozimu/LanguageClient-neovim](https://github.com/autozimu/LanguageClient-neovim) and i'm trying to use the rename functionality. But when I do I get a:
`Method LanguageServer\Server\TextDocument::rename() does not exist`

Can a rename feature be implemented? It's imperative for me because I refactor my code all the time.

Cheers!

**Comment by felixfbecker** [comment] 2018-02-13 19:18
Duplicate of https://github.com/felixfbecker/php-language-server/issues/21

**Closed by felixfbecker** 2018-02-13 19:18 UTC

**Comment by erlangparasu** [comment] 2019-05-02 06:49
wating for `rename` feature :) +1
