### ISSUE TITLE
No code intelligence inside namespaces

### ISSUE THREAD

**Issue by scriptcoded** [felixfbecker/php-language-server#402] opened 2017-06-12 09:24 UTC
While working with classes or similar, where functions are guarateed to be available but not included in the same file, one should be able have these functions autocompleted. Either by using some sort of config file or some custom annotation format.

**Comment by felixfbecker** [comment] 2017-06-12 09:26
I don't understand, what is not working? Please provide reproduction steps

**Comment by scriptcoded** [comment] 2017-06-12 09:39
Say we've got the following three files:

`User.php`
```php
<?php 

class User {
    
  function __construct() {
      
  }

}
```

`util.php`
```php
<?php

function generateId() {
  return rand(0, 99);
}
```

`load.php`
```php
<?php

include "util.php";
include "User.php";

$user = new User();

```

Then `generateId()` is obviously available in `Ùser.php`, but of course it is not guaranteed, since we don't actually know if `util.php` is included when working in `User.php`.

So the request is to implement some form of feature that allows for defining that `util.php` will be available, so that we can have autocomplete for those functions too.

**Comment by MadHed** [comment] 2017-06-12 09:52
Autocomplete for functions should be working regardless of require/include.
If this doesn't work there must be a bug.

**Comment by felixfbecker** [comment] 2017-06-12 10:22
Cannot reproduce

![image](https://user-images.githubusercontent.com/10532611/27029696-bc3f724a-4f69-11e7-966f-17fd63304a4a.png)

**Comment by scriptcoded** [comment] 2017-06-12 12:06
Ok, so I've traced the problem to being the User class existing within a namespace. So if `user.php` is like

```
<?php 

namespace Test;

class User {
    
  function __construct() {
      
  }

}
```

It won't work

**Comment by felixfbecker** [comment] 2017-06-13 17:21
Duplicate of #380

**Closed by felixfbecker** 2017-06-13 17:21 UTC
Labels: Resolution: Irreproducable
