### ISSUE TITLE
Formatting makes LS non-responsive

### ISSUE THREAD

**Issue by kaloyan-raev** [felixfbecker/php-language-server#144] opened 2016-11-08 17:36 UTC
If I call the Format action then:

1. The document is not formatted.
2. The language server becomes non-responsive. Nothing else seems to work anymore.

This seems to be a recent regression.

**Comment by mniewrzal** [comment] 2016-11-14 09:34
I can reproduce it too.

**Comment by mniewrzal** [comment] 2016-11-14 12:56
I found out that problem is caused by CodeSniffer code. CS is trying to read values from STDIN and after that LS is not responsive. I'm not sure how exactly this affects LS but without this code everything works ok.

https://github.com/squizlabs/PHP_CodeSniffer/blob/2.7.0/CodeSniffer/CLI.php#L406

**Comment by felixfbecker** [comment] 2016-11-14 12:57
Why is it running that code when we are using the programmatic API though?

**Comment by mniewrzal** [comment] 2016-11-14 13:03
CodeSniffer API looks to be far from perfect in this case.

**Comment by felixfbecker** [comment] 2016-11-14 13:06
I'm not even sure if I want to keep formatting inside the LS. It made sense when we could do it from the AST, but now we use CodeSniffer. If a user uses a different linter, we cannot support it. And we also only use it for the formatting, not for linting. It is also the only reason we keep the string content in memory in addition to the AST. It might make more sense to build CodeSniffer support as a separate LS.

**Comment by kaloyan-raev** [comment] 2016-11-14 13:22
CodeSniffer can be used for static code analysis too, i.e. for producing more diagnostics.

The string content is not kept in memory just for CodeSniffer. The LS has the obligation to do it for any document that is currently opened, i.e. has a didOpen notification, but not yet a didClose.

I don't see any benefit of excluding CodeSniffer from this language server. It is resource efficient to have most, if not all, intellisense features in a single language server.

**Comment by felixfbecker** [comment] 2016-11-15 18:59
@mniewrzal Could you report this to CodeSniffer? They should not interact with command lines, STDIN or STDOUT when used programmatically

**Comment by mniewrzal** [comment] 2016-11-15 20:36
Sure, I agree that this should be fixed on their side.

**Closed** 2016-11-18 13:25 UTC
Labels: bug
