### ISSUE TITLE
$this not supported

### ISSUE THREAD

**Issue by IAJcraftDev** [felixfbecker/php-language-server#330] opened 2017-03-10 10:26 UTC
Hi, I tried to use a class located variable in __construct.
![image](https://cloud.githubusercontent.com/assets/12152768/23791587/009c4420-059d-11e7-904e-6999407d9cef.png)

But, if I use a new class instance of the current class:
![image](https://cloud.githubusercontent.com/assets/12152768/23791463/81605f52-059c-11e7-9a97-8ec42bc30b2b.png)

**Comment by haringsrob** [comment] 2017-03-10 11:56
I think this will be solved in https://github.com/felixfbecker/php-language-server/pull/247

This is a duplicate of #195?

**Comment by IAJcraftDev** [comment] 2017-03-10 13:33
Yes, it is. Thank you and sorry for the duplicate.

**Closed** 2017-03-10 13:34 UTC
