### ISSUE TITLE
Take into account case insensitivity

### ISSUE THREAD

**Issue by dimadin** [felixfbecker/php-language-server#552] opened 2017-12-13 18:26 UTC
Names of functions, classes, or methods [are](https://stackoverflow.com/a/33273959) case insensitive in PHP. But for VS Code PHP IntelliSense, they are.

For example, if you name function `abc()`, you wont find its definition or references if you use it like `ABC()`.

**Comment by felixfbecker** [comment] 2018-02-11 01:30
Duplicate of https://github.com/felixfbecker/php-language-server/issues/69

**Closed by felixfbecker** 2018-02-11 01:30 UTC
