### ISSUE TITLE
Jump to declaration multiple workspaces

### ISSUE THREAD

**Issue by jasonbronson** [felixfbecker/php-language-server#664] opened 2018-08-02 15:47 UTC
Jump to declaration goes to incorrect files in another folder in workspace when using multiple files with same file and method names.

VSCode Version: 1.25.1
OS Version: 10.13.6 OSX
Steps to Reproduce:

While setting this up for you I realized you don't even need a workspace for this issue. Just two folders does the trick.

Step 1 create a folder vscodebug
Step 2 open in vscode the folder with my github repo in it
https://github.com/jasonbronson/BugVSCode
Step 3 open up posts.php under this folder in editor
/pcentral/wp-content/themes/theme1/libraries/posts.php
Step 4 close the posts.php file
Step 5 open up pressreleases.php file under
/pmasters/wp-content/themes/theme2/libraries/pressreleases.php
Step 6 Highlight "Posts" under Pressrelease extends Posts
Step 7 hit go to declaration
Step 8 notice it jumps to the top folder with that file.

I believe if you're in a folder the top level would be all that it should be searching for not going to other folders.
Example I open up top folder 1 to copy some code into the library file I'm building into folder2 now this bug occurs.

**Comment by Ciantic** [comment] 2018-10-09 13:39
This probably does not have a support for multiple folders yet. Quote from [workspace support in VSCode](https://github.com/Microsoft/vscode/wiki/Extension-Authoring:-Adopting-Multi-Root-Workspace-APIs#do-i-need-to-do-anything):

> If you are implementing a language server then you are affected since up to now a language server only had to handle a single folder. In the new multi-folder setup, a language server should be able to handle multiple folders. See the section 'Language Client/Language Server' below.

So the language server must have a possibility to index multiple arbitrary folders, and make them work as one.

**Comment by Ciantic** [comment] 2018-11-11 19:07
This is duplicate of https://github.com/felixfbecker/php-language-server/issues/513

**Comment by felixfbecker** [comment] 2018-11-11 19:11
@Ciantic thanks! Duplicate of #513

**Closed by felixfbecker** 2018-11-11 19:11 UTC
