### ISSUE TITLE
[Feature Request] Setting for ignoring folders.

### ISSUE THREAD

**Issue by alanaasmaa** [felixfbecker/php-language-server#556] opened 2017-12-20 11:13 UTC
Hi, i would like to ignore some folders in my code.

For an example i use (history extension)[https://marketplace.visualstudio.com/items?itemName=xyz.local-history] and i would not like to see suggestions and definitions from this folder.

**Comment by felixfbecker** [comment] 2017-12-20 11:14
Duplicate of https://github.com/felixfbecker/php-language-server/issues/159

**Closed by felixfbecker** 2017-12-20 11:14 UTC
